### ISSUE TITLE
error TS2314: Generic type 'ErrorObservable<T>' requires 1 type argument(s)

### ISSUE THREAD

**Issue by IvanIFJ** [ghidoz/angular2-jsonapi#190] opened 2018-08-02 13:00 UTC
**ERROR in node_modules/angular2-jsonapi/dist/services/json-api-datastore.service.d.ts(40,40): error TS2314: Generic type 'ErrorObservable<T>' requires 1 type argument(s).**

Reproducing the error:

`ng new app-test`
`npm i -S angular2-jsonapi`
`npm i -S rxjs-compat@6`

`ng serve`
> **ERROR in node_modules/angular2-jsonapi/dist/services/json-api-datastore.service.d.ts(40,40): error TS2314: Generic type 'ErrorObservable<T>' requires 1 type argument(s).**

**Env infos:**
Angular CLI: 6.1.2
Node: 10.3.0
OS: win32 x64
Angular: 6.1.0

**Packages:**
angular2-jsonapi: ^5.0.0
rxjs: ^6.0.0
rxjs-compat ^6.2.2

> Workaround:
> Go to node_modules/angular2-jsonapi/dist/services/json-api-datastore.service.d.ts(40,40);
> Add type any to this ErrorObservable:
> `protected handleError(error: any): ErrorObservable<any>;`

**Comment by safo6m** [comment] 2018-08-06 17:48
@IvanIFJ did you try angular2-jsonapi version v6.0.0-beta which is compatible with rxjs@6?

**Comment by IvanIFJ** [comment] 2018-08-07 13:11
Hi @safo6m,
I did, but version 6 still on Beta already.
And I had the same issue.

> ERROR in node_modules/angular2-jsonapi/dist/services/json-api-datastore.service.d.ts(40,40): error TS2314: Generic type 'ErrorObservable<T>' requires 1 type argument(s).

**Comment by KariiO** [comment] 2018-08-13 07:11
Same here - probably published version 6.0.0-beta is not really updated and sources are old.

**Comment by emmanueldaher** [comment] 2018-08-13 20:15
Same here, even using v6.0.0-beta.

**Comment by safo6m** [comment] 2018-08-20 21:29
@IvanIFJ @mathisloge @KariiO @emmanueldaher 
The new angular compiler changed the build structure.
This should be fixed in v6.0.2-beta.

**Comment by mathisloge** [comment] 2018-08-21 19:09
That fixed it for me

**Comment by emmanueldaher** [comment] 2018-08-21 20:17
@IvanIFJ , @safo6m , @KariiO , @mathisloge 

The problem is fixed in v6.0.2-beta.

This issue should be closed! =)

**Closed** 2018-08-22 11:07 UTC
