### ISSUE TITLE
saveRecord return model even on error response

### ISSUE THREAD

**Issue by Jerga99** [ghidoz/angular2-jsonapi#133] opened 2017-11-23 12:32 UTC
There is something with implementation of saveRecord after we updated library, our app is not working correctly anymore. When we got error response,  service returns always Model. 

return httpCall
      .map((res) => res.status === 201 ? this.extractRecordData(res, modelType, model) : model)
      .catch((error) => {
        console.error(error);
        return Observable.of(model);
      })
      .map((res) => this.resetMetadataAttributes(res, attributesMetadata, modelType))
      .map((res) => this.updateRelationships(res, relationships))
      .catch((res) => this.handleError(res));
  }

First catch is not necessary and should be removed. Second catch is never called... I dont know this part of code seems little messy for me. Can I make PR to fix this issue ? (Works correctly for us after delete of first catch)

**Comment by MariiaPunda** [comment] 2017-11-27 12:09
@safo6m @HennerM
Can you, please, check this issue? 
Can't upgrade app to be able to use metadata, because error response is broken now.

**Comment by HennerM** [comment] 2017-12-14 17:23
I merged the PR and released 4.0.2, can you verify if this is still an issue?

**Comment by MariiaPunda** [comment] 2018-01-17 16:29
Issue is not reproducible anymore, tested with version 4.0.3

**Closed** 2018-02-11 20:38 UTC
